apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentask-data
  namespace: agentask
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
