apiVersion: v1
kind: Service
metadata:
  name: agentask
  namespace: agentask
spec:
  type: ClusterIP
  selector:
    app: agentask
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
